### PR TITLE
Updating opts to enable overriding all algo parameters

### PR DESCRIPTION
**Pull request by lupesko**
Hi!

I've recently used this cool package but to get the results I was looking for I had to override some of the algo HSL, quality and weight params.
This change enables providig all algo params through the opts constructor argument.

I also updated readme.md with params documentation.

### CODE REVIEW

**Comment by akfish** [comment]
Thanks a lot. Looks good. I'll review and merge it soon.

**Comment by lupesko** [comment]
Sounds good.
I was also thinking of a small optimization enabling clients to ask for the specific swatches they require. This should make it run much faster for the cases where only Vibrant swatch is required.
WDYT?

**Comment by akfish** [comment]
Hi, I just noticed that there are too many diff noise from compiled files /lib/*.js. Maybe it's because you are using a different platform setup? I compiled it on my end and only got 6 changed files instead of 13. I could cherry pick the changes but not without losing your commit messages in the code base. So if you could send another PL with uncompiled files only (README.md and vibrant.coffee), that would be great.

As for your optimization proposal, let me setup a benchmark to identify the hotspot and see what we can find.

**Comment by akfish** [comment]
```
Sampling: 8ms
Quantize: 63ms
cmap.vboxes.map: 0ms
findMaxPopulation: 0ms
generateVarationColors: 1ms
generateEmptySwatches: 0ms
      √ 1.jpg (168ms)
Sampling: 11ms
Quantize: 45ms
cmap.vboxes.map: 0ms
findMaxPopulation: 0ms
generateVarationColors: 1ms
generateEmptySwatches: 0ms
      √ 2.jpg (111ms)
Sampling: 13ms
Quantize: 53ms
cmap.vboxes.map: 0ms
findMaxPopulation: 0ms
generateVarationColors: 0ms
generateEmptySwatches: 0ms
      √ 3.jpg (109ms)
Sampling: 10ms
Quantize: 38ms
cmap.vboxes.map: 0ms
findMaxPopulation: 0ms
generateVarationColors: 0ms
generateEmptySwatches: 0ms
      √ 4.jpg (109ms)
```

So I wrapped key stages in `Vibrant._process` method with `console.time` and `console.timeEnd` and got the above result. As you can see the hostspots are at sampling and quantization stages, while the swatch generation stage didn't even register by the timer. I could try higher precision timer but I doubt it would make much of a difference. 
Based on those preliminary data, there seems to be little gain by making the proposed optimization.

**Comment by lupesko** [comment]
I've updated the original commit with a commit that reverts it and another commits that does only the minimal changes.

Let me know if this works.

**Comment by lupesko** [comment]
Let's continue the discussion on the optimization on another thread.

**Comment by akfish** [comment]
That worked great. Thanks. Merged and published as version 1.1.5.

**Pull request merged**
