### PR TITLE
[WIP] Refactor/monorepo merge

### PR DESCRIPTION
**Pull request by akfish**
This PR tracks the merge process from `refactor/monorepo-merge` to `develop`. Once merged and stable:
* Create new branch `legacy` on `procrastination-recovery`(from #81, which should be merged to `master` by then) for tracking purpose. A maintenance version will be published as well.
* Reset `master` -> `develop`.

Monorepo will become the main development line.

Thanks @crutchcorn's hard work for making this happen.

### CODE REVIEW

**Comment by akfish** [comment]
Here's what we have done so far:
- [x] Work form #81 
- [x] Build configurations
- [x] Test configurations
- [x] Linter configuration
- [x] Enable `strictNullChecks`
- [x] Remove dependencies to `lodash`, `url` (Equivalent to #84)

What's missing:
- [ ] Better docs (code docs, examples, guides and etc)
- [ ] More test coverage (if needed)

Version `3.1.0-alpha.1` is published to npm.

@crutchcorn I believe we are ready to merge this PR. Further work can be completed down the road. Could you please take a look and see if there's anything missing?

**Comment by crutchcorn** [comment]
I did a quick run-though of the commits made and the things look good to go.

That being said, I'd personally love to see a `CHANGELOG.md` file with at least the v3.0 and v3.1 changes in there (I think we could add more of the previous versions in the future and even have something like [this](https://github.com/conventional-changelog/conventional-changelog) to potentially generate them automatically in the future, if we wanted to standardize on commit messages (and could enforce this using something like [husky](https://github.com/typicode/husky)

Looking ahead, I think I'll prioritize docs and guides next (especially with the monorepo breaking things into their own packages).

**Comment by akfish** [comment]
Change log is a good idea.

For documentations, I think we could do code docs first. They can be consumed via IDE's code intelligence. And documents can be automatically generated from them. 

I did try `typedoc` with `typedoc-plugin-markdown` while working on this PR. I intended to generate code docs in Markdown format and put them under `documentations` folder at repo root level. Though it doesn't support monorepo well out-of-box. I just didn't have enough time to tweak it. But we can stick to its syntax first, and worry about the tooling later.

Some example projects would be nice too. 

The project structure I had in mind should be something like this:
```
node-vibrant/
├── fixtures/
├── packages/
├── documentations/ <- docs in Markdown format here
├── examples/ <- example projects
├── README.md
```

I'll merge this PR and see how it turns out then. :)

**Comment by akfish** [comment]
Oops. I thought the version number looks funny somehow. I'll fix it right
away.

**Pull request merged**
