### PR TITLE
Remove lodash dependency

### PR DESCRIPTION
**Pull request by NotWoods**
Replaces use of lodash with built-in modules, slimming down the browser build.

Additionally replaced the old node `'url'` module with the global `URL` object that works in browsers, and cleaned up some unused imports.

### CODE REVIEW

**Comment by crutchcorn** [comment]
This was something I was hoping to do after some of the work on #82 was wrapped up. I'd love to review this and see if we can get it into there. (rather than into the current `master` non-mono-repo style)

What are your thoughts, @akfish?

**Comment by akfish** [comment]
It so happens that I was on the same track earlier, when I did a bundle analyze on the `monorepo` branch. Lodash costs use a few hundreds kBs for just a few simple functions. We should definitely replace it. 


Since the monorepo branch is almost ready. I will not merge any new PRs to the old branch. Sorry. :)

**Comment by NotWoods** [comment]
Fair enough, I'll try again once the monorepo is ready!

**Comment by akfish** [comment]
Thanks for the PR anyway!

**Comment by akfish** [comment]
Lodash removed in 0e56671, 7747c3e.
Use `URL` in 3825e61.

**Pull request closed without merging**
