### PR TITLE
Image url

### PR DESCRIPTION
**Pull request by pbrandt1**
load urls with http or https.

### CODE REVIEW

**Comment by pbrandt1** [comment]
#4

**Comment by ScottKriegerPD** [comment]
I can confirm that this is working for me. Thanks @pbrandt1 !

**Comment by akfish** [comment]
Looks good. Only 2 small issues:

* `examples/node-test.js` is not needed. Since all tests should be written as Mocha specs.
* Compiled files are causing too many diff noises. Some cross-platform mess-ups with the coffee-script I think. This has happened before and I should mentioned it somewhere in the doc.

So if you could remove `examples/node-test.js` and revert compiled files, that would be great.

**Comment by pbrandt1** [comment]
reverted commits to lib (disappointed i had to, though).  renamed node-test to node-example b/c it's an example not a test.  hopefully that's okay.

**Comment by akfish** [comment]
Looks OK for now. Sorry for the inconvenience.

**Comment by akfish** [comment]
Published as 1.2.0

**Pull request merged**
